# config.py

# ==============================
# Palabras clave típicas de imágenes generadas con IA
# ==============================
etiquetas_excluidas = ["SourceFile", "FileName"] 

PALABRAS_CLAVE_IA = [
    "GPT-4o", "OpenAI API", "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia",
    "c2pa", "Microsoft Responsible AI Image ", "Made with Google AI", "Image Creator from Designer", 
    "Adobe Firefly", "Ideogram AI", "prompt", "model", "ChatGPT", "Azure OpenAI ImageGen","Image Creator from Designer",
    "GPT-4o, OpenAI API","(c2pa)-0011-0010-800000aa00389b71","c2pa","c2pa.created","originalPrompt",
    "Microsoft Sora Video Provenance", "Microsoft Video Provenance","KSampler","model","Created using InVideo AI"
]

PALABRAS_POSIBLES_IA = [
    "Unknown (saws)", "Unknown (hand)", "CC0","generated by python-docx","python-docx","Microsoft Macintosh Word","Microsoft Word 12.0.0",
    "WeasyPrint 65.1","PyFPDF 1.7.2 http://pyfpdf.googlecode.com/","Skia/PDF m83","Chromium","Skia/PDF m127",
    "jsPDF 2.5.1","generated using python-pptx","2013:01:27 09:14:16Z", "Microsoft Macintosh PowerPoint","Unknown Creator",
    "LibreOffice/25.2.4.3$Linux_X86_64","Lavf58.20.100","Lavf57.56.101","Lavf58.45.100","Lavf61.1.100","Lavf58.20.100",
    "Lavf60.16.100","Lavf62.0.100","Lavf59.27.100","Lavf61.1.100","Lavf58.29.100",
    "CREATOR: gd-jpeg v1.0 (using IJG JPEG v62)", "[minor] Text/EXIF chunk(s) found after PNG IDAT (may be ignored by some readers) [x2]"
]

NUMEROS_FECHAS_CLAVE = [
    "2013:12:23 23:15:00Z", "12.0000", "2023:08:21 21:53:30Z", "0000:00:00 00:00:00", "1980"
]

ETIQUETAS_MODELO = {
    "GPT-4o": "GPT-4o (DALLE)", "Azure OpenAI ImageGen": "GPT-4/5 (DALLE)", "Made with Google AI": "IMAGEN (Google)",
    "Microsoft Responsible AI Image Provenance": "GPT-4/5 (DALLE)", "OpenAI API": "GPT-4o (DALLE)", "originalPrompt": "StableDifusion",
    "Ideogram AI": "Ideogram", "CREATOR: gd-jpeg v1.0 (using IJG JPEG v62)": "Multimodelo", "generated by python-docx":"GPT4/5 (OpenAI)",
    "12.0000": "GPT4/5 (OpenAI)", "PyFPDF 1.7.2 http://pyfpdf.googlecode.com/":"GPT4/5 (OpenAI)", "generated using python-pptx":"GPT4/5 (OpenAI)",
    "Lavf60.16.100": "SORA (OpenAI)", "Microsoft Video Provenance": "SORA (OpenAI)", "prompt": "StableDifusion",
}

ETIQUETAS_APLICACION = {
    "ChatGPT": ["ChatGpt"], "Azure OpenAI ImageGen": ["Copilot"], "Image Creator from Designer": ["Bing"], "API": ["Perplexiti"],
    "Adobe Firefly": ["Adobe Firefly"], "Ideogram AI": ["ideogram"], "prompt": ["Raphael", "StableDifusion", "Giz"],
    "Created using InVideo AI.": ["InVideoAI"], "Microsoft Video Provenance": ["Bing"], "generated by python-docx": ["ChatGpt", "Perplexiti"]
}

ETIQUETAS_POSIBLE_APLICACION = {
    "Microsoft Word 12.0.0": ["Aidocmaker"], "12.000": ["chatgpt","aidocmaker"], "WeasyPrint 65.1": ["aidockmaker"],
    "Skia/PDF ": ["Hotform","perplexiti"], "CREATOR: gd-jpeg v1.0 (using IJG JPEG v62)": ["aidcokmaekr"],
    "[minor] Text/EXIF chunk(s) found after PNG IDAT (may be ignored by some readers) [x2]": ["PicktoAITools"],
    "PyFPDF 1.7.2 http://pyfpdf.googlecode.com/": ["Chatgpt"], "jsPDF": ["templanet"], "generated using python-pptx": ["ChatGpt"],
    "2023:08:21 21:53:30Z": ["aidocmaker"], "LibreOffice/25.2.4.3$Linux_X86_64 ": ["slidesgo"],
    "Lavf": ["ChatGpt","DreamLux","AiFreeVideo","perplixiti","kapwing","Lunai","Midjourney","Pixverse","Vidfull","MetaAI"], "CC0": ["Openart"]
}
