import sys
from PyQt6.QtWidgets import (
    QApplication, 
)
from PyQt6.QtGui import  QPalette, QColor  
from PyQt6.QtCore import Qt
from Gui import DetectorImagenIA

def main():
    app = QApplication(sys.argv)

    # Configurar tema oscuro
    paleta_oscura = QPalette()
    paleta_oscura.setColor(QPalette.ColorRole.Window, QColor(53, 53, 53))
    paleta_oscura.setColor(QPalette.ColorRole.WindowText, Qt.GlobalColor.white)
    paleta_oscura.setColor(QPalette.ColorRole.Base, QColor(35, 35, 35))
    paleta_oscura.setColor(QPalette.ColorRole.AlternateBase, QColor(53, 53, 53))
    paleta_oscura.setColor(QPalette.ColorRole.ToolTipBase, Qt.GlobalColor.white)
    paleta_oscura.setColor(QPalette.ColorRole.ToolTipText, Qt.GlobalColor.white)
    paleta_oscura.setColor(QPalette.ColorRole.Text, Qt.GlobalColor.white)
    paleta_oscura.setColor(QPalette.ColorRole.Button, QColor(53, 53, 53))
    paleta_oscura.setColor(QPalette.ColorRole.ButtonText, Qt.GlobalColor.white)
    paleta_oscura.setColor(QPalette.ColorRole.BrightText, Qt.GlobalColor.red)
    paleta_oscura.setColor(QPalette.ColorRole.Highlight, QColor(142, 45, 197))
    paleta_oscura.setColor(QPalette.ColorRole.HighlightedText, Qt.GlobalColor.black)
    app.setPalette(paleta_oscura)
    app.setStyleSheet("QToolTip { color: #ffffff; background-color: #2a82da; border: none; }")

    ventana = DetectorImagenIA()
    ventana.show()

    sys.exit(app.exec())

if __name__ == "__main__":
    main()



"""

import sys
import subprocess
import json
import shutil
from datetime import datetime
import os
from PyQt6.QtWidgets import (
    QApplication, QWidget, QLabel, QPushButton, QFileDialog, QVBoxLayout, QHBoxLayout,
    QTextEdit, QTableWidget, QTableWidgetItem, QTabWidget, QMenuBar, QProgressBar, QDialog
)
from PyQt6.QtGui import QFont, QAction, QPalette, QColor,  QTextFormat
from PyQt6.QtCore import Qt, QThread, pyqtSignal

# ==============================
# Palabras clave típicas de imágenes generadas con IA
# ==============================
etiquetas_excluidas= ["SourceFile", "FileName"] 

PALABRAS_CLAVE_IA = [
    "GPT-4o", "OpenAI API", "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia",
    "c2pa", "Microsoft Responsible AI Image ", "Made with Google AI", "Image Creator from Designer", 
    "Adobe Firefly", "Ideogram AI", "prompt", "model", "ChatGPT", "Azure OpenAI ImageGen","Image Creator from Designer",
    "GPT-4o, OpenAI API","(c2pa)-0011-0010-800000aa00389b71","c2pa","c2pa.created","originalPrompt",
    "Microsoft Sora Video Provenance", "Microsoft Video Provenance","KSampler","model","Created using InVideo AI"
    
]

PALABRAS_POSIBLES_IA =[
    "Unknown (saws)", "Unknown (hand)", "CC0","generated by python-docx","python-docx","Microsoft Macintosh Word","Microsoft Word 12.0.0"
    ,"WeasyPrint 65.1","PyFPDF 1.7.2 http://pyfpdf.googlecode.com/","Skia/PDF m83","Chromium","Skia/PDF m127"
    ,"jsPDF 2.5.1","generated using python-pptx","2013:01:27 09:14:16Z", "Microsoft Macintosh PowerPoint","Unknown Creator"
    ,"LibreOffice/25.2.4.3$Linux_X86_64","Lavf58.20.100","Lavf57.56.101","Lavf58.45.100","Lavf61.1.100","Lavf58.20.100"
    ,"Lavf60.16.100","Lavf62.0.100","Lavf59.27.100","Lavf61.1.100","Lavf58.29.100"
    "CREATOR: gd-jpeg v1.0 (using IJG JPEG v62)", "[minor] Text/EXIF chunk(s) found after PNG IDAT (may be ignored by some readers) [x2]"
]

NUMEROS_FECHAS_CLAVE = [
    "2013:12:23 23:15:00Z","12.0000" , "2023:08:21 21:53:30Z", "0000:00:00 00:00:00","1980"
    
]

ETIQUETAS_MODELO = {
     "GPT-4o": "GPT-4o (DALLE)", "Azure OpenAI ImageGen": "GPT-4/5 (DALLE)", "Made with Google AI": "IMAGEN (Google)", 
     "Microsoft Responsible AI Image Provenance": "GPT-4/5 (DALLE)", "OpenAI API": "GPT-4o (DALLE)", "originalPrompt": "StableDifusion",
     "Ideogram AI": "Ideogram", "CREATOR: gd-jpeg v1.0 (using IJG JPEG v62)": "Multimodelo", "generated by python-docx":"GPT4/5 (OpenAI)",
     "12.0000":"GPT4/5 (OpenAI)","PyFPDF 1.7.2 http://pyfpdf.googlecode.com/":"GPT4/5 (OpenAI)","generated using python-pptx":"GPT4/5 (OpenAI)",
     "Lavf60.16.100":"SORA (OpenAI)","Microsoft Video Provenance":"SORA (OpenAI)","prompt":"StableDifusion",  
   }

ETIQUETAS_APLICACION ={
    "ChatGPT":["ChatGpt"], "Azure OpenAI ImageGen":["Copilot"],"Image Creator from Designer":["Bing"], "API":["Perplexiti"],
    "Adobe Firefly":["Adobe Firefly"],"Ideogram AI":["ideogram"], "prompt":["Raphael","StableDifusion","Giz"],
    "Created using InVideo AI.":["InVideoAI"], "Microsoft Video Provenance":["Bing"], "generated by python-docx":["ChatGpt","Perplexiti"]
}

ETIQUETAS_POSIBLE_APLICACION ={
    "Microsoft Word 12.0.0":["Aidocmaker"],"12.000":["chatgpt","aidocmaker"],   "WeasyPrint 65.1":["aidockmaker"],
     "Skia/PDF ":["Hotform","perplexiti"],"CREATOR: gd-jpeg v1.0 (using IJG JPEG v62)":["aidcokmaekr"], "[minor] Text/EXIF chunk(s) found after PNG IDAT (may be ignored by some readers) [x2]":["PicktoAITools"],
    "PyFPDF 1.7.2 http://pyfpdf.googlecode.com/":["Chatgpt"],"jsPDF":["templanet"],"generated using python-pptx":["ChatGpt"],
    "2023:08:21 21:53:30Z":["aidocmaker"], "LibreOffice/25.2.4.3$Linux_X86_64 ":["slidesgo"],
    "Lavf":["ChatGpt","DreamLux","AiFreeVideo","perplixiti","kapwing","Lunai","Midjourney","Pixverse","Vidfull","MetaAI"], "CC0":["Openart"]
}

def es_fecha(val):
    formatos = ["%Y:%m:%d %H:%M:%S", "%Y-%m-%d", "%Y:%m:%d"]
    for fmt in formatos:
        try:
            datetime.strptime(val, fmt)
            return True
        except:
            continue
    return False

def contiene_numero(val):
    return any(c.isdigit() for c in val)

# ==============================
# Función para verificar si una imagen puede ser generada con IA
# ==============================
def verificar_archivo_ia(metadata):
    coincidencias = []
    etiquetas_detectadas = set()

    # Buscar en lista principal PALABRAS_CLAVE_IA
    for clave, valor in metadata.items():
        if clave in etiquetas_excluidas:
            continue
        if clave in etiquetas_detectadas:
            continue
        valor_str = str(valor).lower()

        # Palabras clave IA normales
        for palabra in PALABRAS_CLAVE_IA:
            if palabra and palabra.lower() in valor_str:
                coincidencias.append(f"\nPatrón detectado en '{clave}': {valor}\n")
                etiquetas_detectadas.add(clave)
                break
        if len(coincidencias) >= 3:
            break

    if coincidencias:
        mensaje = "\n".join(coincidencias)
        return True, mensaje

    # Buscar en PALABRAS_POSIBLES_IA y NUMEROS_FECHAS_CLAVE
    coincidencias_posibles = []
    etiquetas_detectadas.clear()

    for clave, valor in metadata.items():
        if clave in etiquetas_excluidas:
            continue
        if clave in etiquetas_detectadas:
            continue

        valor_str = str(valor).lower()

        # Primer buscar coincidencias en PALABRAS_POSIBLES_IA
        encontrado = False
        for palabra in PALABRAS_POSIBLES_IA:
            if palabra and palabra.lower() in valor_str:
                coincidencias_posibles.append(f"Patrón sospechoso detectado en '{clave}': {valor}")
                etiquetas_detectadas.add(clave)
                encontrado = True
                break
        
        # Si no se encontró en arriba, buscar en lista de números/fechas específicas
        if not encontrado:
            for patron_num_fecha in NUMEROS_FECHAS_CLAVE:
                if patron_num_fecha.lower() in valor_str:
                    coincidencias_posibles.append(f"Patrón numérico o fecha sospechosa en'{clave}': {valor}")
                    etiquetas_detectadas.add(clave)
                    break

        if len(coincidencias_posibles) >= 3:
            break

    if coincidencias_posibles:
        mensaje = "\n".join(coincidencias_posibles)
        aviso = "\nNo es posible confirmar generación por IA, pero contiene metadatos sospechosos."
        return None, f"{mensaje}\n{aviso}"

    return False, "\nNo se encontraron patrones típicos de IA ni metadatos sospechosos."

# ==============================
# Función para verificar el modelo con el que fue generado el archivo
# ==============================
def detectar_modelo(metadata):
    modelo =None
    for  valor in metadata.items():
        valor_str = str(valor).lower()
        for etiqueta, nombre_modelo in ETIQUETAS_MODELO.items():
            if etiqueta.lower() in valor_str:
                return nombre_modelo  # Devuelve la primera coincidencia encontrada
    return "Desconocido"
# ==============================
# Función para verificar la aplicacion con la que fue generado el archivo
# ==============================

def detectar_aplicacion(metadata):
    aplicacion = None

    # Buscar en etiquetas de alta prioridad
    for  valor in metadata.items():
        valor_str = str(valor).lower()
        for etiqueta, aplicaciones in ETIQUETAS_APLICACION.items():
            if etiqueta.lower() in valor_str:
                aplicacion = aplicaciones if len(aplicaciones) > 1 else aplicaciones[0]
                return aplicacion  # Retorna inmediatamente la coincidencia prioritaria

    # Si no encontró, buscar en posibles aplicaciones
    aplicaciones_posibles = set()
    for  valor in metadata.items():
        valor_str = str(valor).lower()
        for etiqueta, aplicaciones in ETIQUETAS_POSIBLE_APLICACION.items():
            if etiqueta.lower() in valor_str:
                aplicaciones_posibles.update(aplicaciones)

    if not aplicaciones_posibles:
        aplicacion = "Desconocido"
    elif len(aplicaciones_posibles) == 1:
        aplicacion = aplicaciones_posibles.pop()
    else:
        aplicacion = list(aplicaciones_posibles)

    return aplicacion
# ==============================
# Funciones específicas para analizar metadata según tipo
# ==============================

def analizar_imagen(ruta_archivo):
    
    #Analiza metadata imágenes png, jpg, jpeg con exiftool
    #Retorna metadata y resultado de análisis IA.
  
    metadata = ejecutar_exiftool(ruta_archivo)
    es_ia, mensaje = verificar_archivo_ia(metadata)
    print(mensaje)
    return metadata, es_ia, mensaje

def analizar_video(ruta_archivo):
    
   # Analiza metadata videos mp4 con exiftool
    
    metadata = ejecutar_exiftool(ruta_archivo)
    es_ia, mensaje = verificar_archivo_ia(metadata)
    print(mensaje)
    return metadata, es_ia, mensaje

def analizar_docx(ruta_archivo):
    
   # Analiza metadata docx con exiftool
    
    metadata = ejecutar_exiftool(ruta_archivo)
    es_ia, mensaje = verificar_archivo_ia(metadata)
    print(mensaje)
    return metadata, es_ia, mensaje

def analizar_pdf(ruta_archivo):
    
   # Analiza metadata pdf con exiftool
    
    metadata = ejecutar_exiftool(ruta_archivo)
    es_ia, mensaje = verificar_archivo_ia(metadata)
    print(mensaje)
    return metadata, es_ia, mensaje

def analizar_xlsx(ruta_archivo):
    
   # Analiza metadata xlsx con exiftool
    
    metadata = ejecutar_exiftool(ruta_archivo)
    es_ia, mensaje = verificar_archivo_ia(metadata)
    print(mensaje)
    return metadata, es_ia, mensaje

def analizar_pptx(ruta_archivo):
    
   # Analiza metadata pptx con exiftool
    
    metadata = ejecutar_exiftool(ruta_archivo)
    es_ia, mensaje = verificar_archivo_ia(metadata)
    print(mensaje)
    return metadata, es_ia, mensaje

# ==============================
# Función general para ejecutar exiftool con JSON
# ==============================
def ejecutar_exiftool(ruta_archivo):
    if shutil.which("exiftool") is None:
        raise FileNotFoundError("ExifTool no está instalado o no se encuentra en el PATH del sistema.")
    resultado = subprocess.run(
        ["exiftool", "-json", ruta_archivo],
        capture_output=True, text=True, check=True
    )
    metadata_lista = json.loads(resultado.stdout)
    if metadata_lista:
        return metadata_lista[0]
    else:
        return {}

# ==============================
# Función para decidir qué analizador usar según extensión
# ==============================
def analizar_metadata_por_tipo(ruta_archivo):
    ext = ruta_archivo.lower().split('.')[-1]
    if ext in ["png", "jpg", "jpeg"]:
        return analizar_imagen(ruta_archivo)
    elif ext == "mp4":
        return analizar_video(ruta_archivo)
    elif ext == "docx":
        return analizar_docx(ruta_archivo)
    elif ext == "pdf":
        return analizar_pdf(ruta_archivo)
    elif ext == "xlsx":
        return analizar_xlsx(ruta_archivo)
    elif ext == "pptx":
        return analizar_pptx(ruta_archivo)
    else:
        raise ValueError(f"Extensión no soportada para análisis: {ext}")

# ==============================
# Hilo para ejecutar análisis sin bloquear la interfaz
# ==============================
class HiloMetadata(QThread):
    progreso = pyqtSignal(int)
    terminado = pyqtSignal(dict, object, str,object,object)  # metadata, es_ia, mensaje
    error = pyqtSignal(Exception)

    def __init__(self, ruta_archivo):
        super().__init__()
        self.ruta_archivo = ruta_archivo

    def run(self):
        try:
            self.progreso.emit(10)
            metadata, es_ia, mensaje = analizar_metadata_por_tipo(self.ruta_archivo)
            aplicacion = detectar_aplicacion(metadata)
            modelo = detectar_modelo(metadata)  
            self.progreso.emit(100)
            self.terminado.emit(metadata, es_ia, mensaje, aplicacion,modelo)
        except Exception as e:
            self.error.emit(e)

# ==============================
# Clase interfaz gráfica sin cambios
# ==============================
class DetectorImagenIA(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Detector de archivos generados por IA")
        self.setFixedSize(1000, 680)
        # Layout principal horizontal
        layout_principal = QHBoxLayout()
        # Menú superior
        self.barra_menu = QMenuBar()
        self.inicializar_menu()
        # Layout vertical que contiene menú + contenido
        layout_vertical = QVBoxLayout()
        layout_vertical.setMenuBar(self.barra_menu)
        layout_vertical.addLayout(layout_principal)
        self.setLayout(layout_vertical)
        # Panel izquierdo con pestañas
        self.pestanas = QTabWidget()
        self.pestanas.setFixedWidth(300)
        layout_principal.addWidget(self.pestanas)
        self.inicializar_pestanas()
        # Panel derecho (análisis IA)
        self.panel_derecho = QWidget()
        layout_derecho = QVBoxLayout()
        layout_derecho.setContentsMargins(15, 15, 15, 15)
        layout_derecho.setSpacing(15)
        self.panel_derecho.setLayout(layout_derecho)
        layout_principal.addWidget(self.panel_derecho)
        # Título de análisis
        self.titulo_analisis = QLabel("Análisis de Archivo")
        self.titulo_analisis.setFont(QFont("Arial", 16, QFont.Weight.Bold))
        layout_derecho.addWidget(self.titulo_analisis, alignment=Qt.AlignmentFlag.AlignLeft)
        # Barra de progreso
        self.barra_progreso = QProgressBar()
        self.barra_progreso.setMinimum(0)
        self.barra_progreso.setMaximum(100)
        self.barra_progreso.hide()
        layout_derecho.addWidget(self.barra_progreso)
        # Estado de análisis
        self.estado_analisis = QLabel("Selecciona un archivo para iniciar el análisis")
        self.estado_analisis.setFont(QFont("Arial", 11))
        layout_derecho.addWidget(self.estado_analisis)
        # Icono resultado
        self.icono_resultado = QLabel()
        self.icono_resultado.setFixedSize(64, 64)
        layout_derecho.addWidget(self.icono_resultado, alignment=Qt.AlignmentFlag.AlignLeft)
        # Texto resultado
        self.texto_resultado = QLabel("")
        self.texto_resultado.setFont(QFont("Arial", 12))
        self.texto_resultado.setWordWrap(True)
        layout_derecho.addWidget(self.texto_resultado)
        # Botón ver metadata completa
        self.boton_ver_metadata = QPushButton("< Ver metadata completa")
        self.boton_ver_metadata.setEnabled(False)
        self.boton_ver_metadata.clicked.connect(self.mostrar_metadata_completa)
        layout_derecho.addWidget(self.boton_ver_metadata, alignment=Qt.AlignmentFlag.AlignLeft)
        # Variables de control
        self.metadata_completa = None
        self._ventana_metadata = None  # Para mantener referencia de QDialog
        self.hilo = None  # Hilo de análisis en curso

    def inicializar_menu(self):
        menu_archivo = self.barra_menu.addMenu("Archivo")
        accion_abrir = QAction("Abrir", self)
        accion_abrir.triggered.connect(self.seleccionar_archivo)
        accion_salir = QAction("Salir", self)
        accion_salir.setShortcut("Ctrl+Q")
        accion_salir.triggered.connect(QApplication.instance().quit)
        menu_archivo.addAction(accion_abrir)
        menu_archivo.addSeparator()
        menu_archivo.addAction(accion_salir)

        menu_escaneo = self.barra_menu.addMenu("Escaneo")
        menu_escaneo.addAction("Escaneo rápido")
        menu_escaneo.addAction("Escaneo profundo")
        menu_escaneo.addSeparator()
        menu_escaneo.addAction("Escanear múltiples archivos")
        menu_escaneo.addAction("Ver resultados recientes")

    def inicializar_pestanas(self):
        widget_ia = QWidget()
        layout_ia = QVBoxLayout()
        layout_ia.setContentsMargins(10, 10, 10, 10)
        layout_ia.setSpacing(10)
        widget_ia.setLayout(layout_ia)
        self.boton_seleccionar = QPushButton("Seleccionar archivo")
        self.boton_seleccionar.clicked.connect(self.seleccionar_archivo)
        layout_ia.addWidget(self.boton_seleccionar)
        etiqueta_metadata = QLabel("Metadata extraída")
        etiqueta_metadata.setFont(QFont("Arial", 11, QFont.Weight.Bold))
        layout_ia.addWidget(etiqueta_metadata)
        self.tabla_metadata = QTableWidget(0, 2)
        self.tabla_metadata.setHorizontalHeaderLabels(["Campo", "Valor"])
        self.tabla_metadata.verticalHeader().setVisible(False)
        self.tabla_metadata.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.tabla_metadata.setSelectionMode(QTableWidget.SelectionMode.NoSelection)
        self.tabla_metadata.setFixedHeight(150)
        self.tabla_metadata.horizontalHeader().setStretchLastSection(True)
        layout_ia.addWidget(self.tabla_metadata)
        self.pestanas.addTab(widget_ia, "Detector de IA")
        self.pestanas.addTab(QWidget(), "Archivos")
        self.pestanas.addTab(QWidget(), "Escaneo")
        self.pestanas.addTab(QWidget(), "Acerca de")

    def seleccionar_archivo(self):
        ruta_archivo, _ = QFileDialog.getOpenFileName(
            self,
            "Selecciona un archivo",
            "",
            "Archivos soportados (*.png *.jpg *.jpeg *.mp4 *.docx *.pdf *.xlsx *.pptx)"
        )
        if ruta_archivo:
            self.estado_analisis.setText("Analizando metadata...")
            self.barra_progreso.setValue(0)
            self.barra_progreso.show()
            self.icono_resultado.clear()
            self.texto_resultado.clear()
            self.boton_ver_metadata.setEnabled(False)
            self.hilo = HiloMetadata(ruta_archivo)
            self.hilo.progreso.connect(self.barra_progreso.setValue)
            self.hilo.terminado.connect(self.finalizar_analisis)
            self.hilo.error.connect(self.manejar_error)
            self.hilo.start()

    def finalizar_analisis(self, metadata, es_ia, mensaje, aplicacion, modelo):
        self.metadata_completa = metadata
        self.llenar_tabla_metadata(metadata)
        self.estado_analisis.setText("")
    
        if es_ia is True:
            self.icono_resultado.setText("❌")
            texto = f"<b>Resultado de análisis:</b> Archivo generado por IA<br>"
            texto += f"La aplicación con la que fue generado el archivo fue: {', '.join(aplicacion) if isinstance(aplicacion, list) else aplicacion}<br>"
            texto += f"El modelo de IA usado fue: {modelo if modelo != 'Desconocido' else 'No se pudo determinar el modelo exacto'}<br>"
        
        elif es_ia is None:
            self.icono_resultado.setText("⚠️")
            texto = f"<b>Resultado de análisis:</b> Posible generación por IA (no confirmado)<br>"
            texto += f"Se cree que el archivo pudo ser generado por: {', '.join(aplicacion) if isinstance(aplicacion, list) else aplicacion}<br>"
            texto += f"Se cree que el modelo de IA usado fue: {modelo if modelo != 'Desconocido' else 'No se pudo determinar el modelo'}<br>"
        
        else:  # es_ia False
            self.icono_resultado.setText("✅")
            texto = "<b>Resultado de análisis:</b> Archivo genuino<br><b>0% IA detectada</b><br>"
            texto += "No se detectó la aplicación con la que fue generado el archivo<br>"
            texto += "No se encontró modelo de IA generativa<br>"

         # clave para interpretar <br> como salto de línea
        self.texto_resultado.setText(f"{texto}<br>{mensaje}")
        self.boton_ver_metadata.setEnabled(True)


    def manejar_error(self, error):
        self.barra_progreso.hide()
        self.estado_analisis.setText(f"⚠️ Error: {error}")

    def llenar_tabla_metadata(self, metadata):
        self.tabla_metadata.setRowCount(0)
        nombre = os.path.basename(metadata.get("SourceFile", "Desconocido"))
        tipo = metadata.get("FileType", metadata.get("MIMEType", "Desconocido"))
        tamano = metadata.get("FileSize", "Desconocido")
        fecha = metadata.get("ModifyDate", metadata.get("DateTimeOriginal", "Desconocida"))
        items = [("Nombre", nombre), ("Tipo", tipo), ("Tamaño", str(tamano)), ("Fecha modificado", fecha)]
        for campo, valor in items:
            fila = self.tabla_metadata.rowCount()
            self.tabla_metadata.insertRow(fila)
            self.tabla_metadata.setItem(fila, 0, QTableWidgetItem(campo))
            self.tabla_metadata.setItem(fila, 1, QTableWidgetItem(str(valor)))

    def mostrar_metadata_completa(self):
        if self.metadata_completa:
            from pprint import pformat
            metadata_str = pformat(self.metadata_completa, indent=2, width=80)
            self._ventana_metadata = QDialog(self)
            self._ventana_metadata.setWindowTitle("Metadata completa")
            self._ventana_metadata.setFixedSize(600, 400)
            layout = QVBoxLayout()
            txt = QTextEdit()
            txt.setPlainText(metadata_str)
            txt.setReadOnly(True)
            layout.addWidget(txt)
            self._ventana_metadata.setLayout(layout)
            self._ventana_metadata.exec()

# ==============================
# Ejecución principal
# ==============================
if __name__ == "__main__":
    app = QApplication(sys.argv)
    paleta_oscura = QPalette()
    paleta_oscura.setColor(QPalette.ColorRole.Window, QColor(53, 53, 53))
    paleta_oscura.setColor(QPalette.ColorRole.WindowText, Qt.GlobalColor.white)
    paleta_oscura.setColor(QPalette.ColorRole.Base, QColor(35, 35, 35))
    paleta_oscura.setColor(QPalette.ColorRole.AlternateBase, QColor(53, 53, 53))
    paleta_oscura.setColor(QPalette.ColorRole.ToolTipBase, Qt.GlobalColor.white)
    paleta_oscura.setColor(QPalette.ColorRole.ToolTipText, Qt.GlobalColor.white)
    paleta_oscura.setColor(QPalette.ColorRole.Text, Qt.GlobalColor.white)
    paleta_oscura.setColor(QPalette.ColorRole.Button, QColor(53, 53, 53))
    paleta_oscura.setColor(QPalette.ColorRole.ButtonText, Qt.GlobalColor.white)
    paleta_oscura.setColor(QPalette.ColorRole.BrightText, Qt.GlobalColor.red)
    paleta_oscura.setColor(QPalette.ColorRole.Highlight, QColor(142, 45, 197))
    paleta_oscura.setColor(QPalette.ColorRole.HighlightedText, Qt.GlobalColor.black)
    app.setPalette(paleta_oscura)
    app.setStyleSheet("QToolTip { color: #ffffff; background-color: #2a82da; border: none; }")
    ventana = DetectorImagenIA()
    ventana.show()
    sys.exit(app.exec())
 """